# Generated by Django 5.2.1 on 2025-06-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_options_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('public', 'Published')], default='draft', max_length=10),
        ),
    ]
