# Generated by Django 5.2.1 on 2025-06-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
