# Generated by Django 5.2.1 on 2025-06-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_category_slug_alter_blog_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
